# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dadi "D.Z." Zhang
email: d236zhan@uwaterloo.ca
description: > # this means to ignore newlines until "baseurl:"
  Dadi "D.Z." Zhang | Coder. Developer. Language enthusiast. Go fanatic. Jays fan. Worships 442.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dzed.me" # the base hostname & protocol for your site
twitter_username: dzklavier
github_username:  dzeedzed

# Build settings
markdown: kramdown

port: 8080
