#
# Configuration
#

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

# site setup
name: Dadi "DZ" Zhang
title: Dadi "DZ" Zhang
description: Student
tagline: Web developer aspiring for expression through code.
url: http://dzed.me
baseurl: ""

author:
  name: Dadi "DZ" Zhang
  email: dzklavier@gmail.com
  uri: http://dzed.me